// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.


export interface Config {
  apiUrl?: string;
  tamboApiKey?: string;
  tamboUrl?: string;
}

export type PublicConfig = Pick<Config, "apiUrl" | "tamboUrl" | "tamboApiKey">;
