// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.


declare global {
  interface ProcessEnv {
    BABYTALK_WEB_API_URL: string;
  }

  interface ImportMetaEnv {
    readonly BABYTALK_WEB_API_URL: string;
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}
