// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.


export interface Config {
  /** PostgreSQL connection string */
  databaseUrl: string;
  /** Secret key for signing JWTs */
  jwtSecret?: string;
  /** HTTP server port */
  port?: number;
  /** Sender email address */
  smtpFrom?: string;
  /** SMTP server hostname */
  smtpHost?: string;
  /** SMTP password (Resend API key for smtp.resend.com) */
  smtpPass?: string;
  /** SMTP server port */
  smtpPort?: number;
  /** SMTP username ('resend' for smtp.resend.com) */
  smtpUser?: string;
  /** Frontend URL for CORS and email links */
  webUrl?: string;
}

export type PublicConfig = Record<string, never>;
