// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.


export interface Config {
  /** PostgreSQL connection string */
  databaseUrl: string;
  /** Secret key for signing JWTs */
  jwtSecret?: string;
  /** HTTP server port */
  port?: number;
  /** SMTP mail configuration */
  smtp?: { from?: string; host?: string; port?: number };
  /** Frontend URL for CORS and email links */
  webUrl?: string;
}

export type PublicConfig = Record<string, never>;
