// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.


declare global {
  interface ProcessEnv {
    /** PostgreSQL connection string */
    BABYTALK_API_DATABASE_URL: string;
    /** Secret key for signing JWTs */
    BABYTALK_API_JWT_SECRET: string;
    /** HTTP server port */
    BABYTALK_API_PORT: string;
    /** Sender email address */
    BABYTALK_API_SMTP_FROM: string;
    /** SMTP server hostname */
    BABYTALK_API_SMTP_HOST: string;
    /** SMTP server port */
    BABYTALK_API_SMTP_PORT: string;
    /** Frontend URL for CORS and email links */
    BABYTALK_API_WEB_URL: string;
  }

  interface ImportMetaEnv {
    /** PostgreSQL connection string */
    readonly BABYTALK_API_DATABASE_URL: string;
    /** Secret key for signing JWTs */
    readonly BABYTALK_API_JWT_SECRET: string;
    /** HTTP server port */
    readonly BABYTALK_API_PORT: string;
    /** Sender email address */
    readonly BABYTALK_API_SMTP_FROM: string;
    /** SMTP server hostname */
    readonly BABYTALK_API_SMTP_HOST: string;
    /** SMTP server port */
    readonly BABYTALK_API_SMTP_PORT: string;
    /** Frontend URL for CORS and email links */
    readonly BABYTALK_API_WEB_URL: string;
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}
