// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.


declare global {
  interface ProcessEnv {
  }

  interface ImportMetaEnv {
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}

export {};
