import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

import { createJiti } from "jiti";

import type { ConfigDefinition } from "../index.js";
import {
  extractJsonSchema,
  formatJsonSchema,
  supportsJsonSchema,
} from "./json-schema.js";
import { generateTypeScript } from "./typescript.js";

export interface GenerateOptions {
  /** Path to the schema source file (TypeScript). Default: "./src/config.ts" */
  schema?: string;
  /** Output path for .gen.ts. Default: "./src/config.gen.ts" */
  outputTs?: string;
  /** Output path for .schema.json. Default: "./src/config.schema.json" */
  outputJson?: string;
  /** Root directory. Default: process.cwd() */
  root?: string;
}

export interface GenerateResult {
  tsPath: string;
  jsonPath: string | null;
}

/**
 * Generate JSON Schema and TypeScript types from a schema source file.
 *
 * The schema file must default-export a defineConfig() call.
 * If the schema library doesn't support StandardJSONSchemaV1,
 * JSON Schema generation is skipped (jsonPath will be null).
 */
export async function generate(
  options: GenerateOptions = {},
): Promise<GenerateResult> {
  const root = resolve(options.root ?? process.cwd());
  const schemaPath = resolve(root, options.schema ?? "./src/config.ts");
  const outputTs = resolve(root, options.outputTs ?? "./src/config.gen.ts");
  const outputJson = resolve(
    root,
    options.outputJson ?? "./src/config.schema.json",
  );

  // Evaluate the TypeScript schema file
  const jiti = createJiti(root, {
    interopDefault: true,
  });
  const mod = await jiti.import(schemaPath);
  const definition = (mod as { default: ConfigDefinition<unknown> }).default;

  if (!definition?.schema) {
    throw new Error(
      `Schema file ${schemaPath} must default-export a defineConfig() call.`,
    );
  }

  let jsonPath: string | null = null;

  if (supportsJsonSchema(definition.schema)) {
    // Extract JSON Schema and generate .gen.ts with full types
    const jsonSchemaObj = extractJsonSchema(definition.schema);
    const jsonSchemaStr = formatJsonSchema(jsonSchemaObj);
    const tsStr = generateTypeScript(jsonSchemaObj, definition);

    mkdirSync(dirname(outputTs), { recursive: true });
    mkdirSync(dirname(outputJson), { recursive: true });
    writeFileSync(outputTs, tsStr, "utf-8");
    writeFileSync(outputJson, jsonSchemaStr, "utf-8");
    jsonPath = outputJson;
  } else {
    // No JSON Schema support — skip JSON Schema file, write minimal .gen.ts
    console.warn(
      "Warning: Schema library does not support StandardJSONSchemaV1. " +
        "Skipping JSON Schema generation. " +
        "TypeScript types will use the schema's inferred types via import.",
    );

    const tsContent = [
      "// This file is auto-generated by @babytalk/standard-config",
      "// Do not edit manually.",
      "//",
      "// Note: JSON Schema generation was skipped because the schema library",
      "// does not support StandardJSONSchemaV1.",
      "",
      `export type { InferOutput as Config } from "${schemaPath}";`,
      "",
    ].join("\n");

    mkdirSync(dirname(outputTs), { recursive: true });
    writeFileSync(outputTs, tsContent, "utf-8");
  }

  return { tsPath: outputTs, jsonPath };
}
