import type { ConfigDefinition } from "../index.js";

const HEADER = `// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.

`;

const primitiveToTS = (type: string | undefined): string => {
  switch (type) {
    case "string": {
      return "string";
    }
    case "number":
    case "integer": {
      return "number";
    }
    case "boolean": {
      return "boolean";
    }
    case "null": {
      return "null";
    }
    default: {
      return "unknown";
    }
  }
};

const jsonSchemaTypeToTS = (schema: Record<string, unknown>): string => {
  const type = schema.type as string | string[] | undefined;

  if (Array.isArray(type)) {
    return type.map((t) => primitiveToTS(t)).join(" | ");
  }

  if (type === "object" && schema.properties) {
    const props = schema.properties as Record<string, Record<string, unknown>>;
    const required = schema.required as string[] | undefined;
    const req = new Set(required);
    const entries = Object.entries(props).map(([k, v]) => {
      const optional = req.has(k) ? "" : "?";
      return `${k}${optional}: ${jsonSchemaTypeToTS(v)}`;
    });
    return `{ ${entries.join("; ")} }`;
  }

  if (type === "array") {
    const items = schema.items as Record<string, unknown> | undefined;
    if (items) {
      return `${jsonSchemaTypeToTS(items)}[]`;
    }
    return "unknown[]";
  }

  return primitiveToTS(type);
};

const flattenPaths = (
  properties: Record<string, Record<string, unknown>>,
  parentPath = ""
): string[] => {
  const paths: string[] = [];

  for (const [key, schema] of Object.entries(properties)) {
    const currentPath = parentPath ? `${parentPath}.${key}` : key;

    if (schema.type === "object" && schema.properties) {
      paths.push(
        ...flattenPaths(
          schema.properties as Record<string, Record<string, unknown>>,
          currentPath
        )
      );
    } else {
      paths.push(currentPath);
    }
  }

  return paths;
};

/**
 * Generate a .gen.ts file content with Config and PublicConfig types,
 * plus an env var name map constant.
 */
export const generateTypeScript = (
  jsonSchema: Record<string, unknown>,
  definition: Pick<
    ConfigDefinition<unknown>,
    "prefix" | "public" | "separator" | "publicPrefix"
  >
): string => {
  const lines: string[] = [HEADER];

  // Generate Config type from JSON Schema properties
  const properties = (jsonSchema.properties ?? {}) as Record<
    string,
    Record<string, unknown>
  >;
  const required = jsonSchema.required as string[] | undefined;
  const requiredSet = new Set(required);

  lines.push("export interface Config {");
  for (const [key, prop] of Object.entries(properties)) {
    const tsType = jsonSchemaTypeToTS(prop);
    const optional = requiredSet.has(key) ? "" : "?";
    lines.push(`  ${key}${optional}: ${tsType};`);
  }
  lines.push("}\n");

  // Generate PublicConfig type
  const publicKeys = definition.public ?? [];
  if (publicKeys.length > 0) {
    const topLevelPublicKeys = publicKeys
      .map((k) => {
        const parts = k.split(".");
        return parts[0];
      })
      .filter((k) => k !== undefined)
      .filter((k, i, arr) => arr.indexOf(k) === i);

    const validKeys = topLevelPublicKeys.filter((k) => k in properties);
    if (validKeys.length > 0) {
      const pickKeys = validKeys.map((k) => `"${k}"`).join(" | ");
      lines.push(`export type PublicConfig = Pick<Config, ${pickKeys}>;\n`);
    } else {
      lines.push("export type PublicConfig = Record<string, never>;\n");
    }
  } else {
    lines.push("export type PublicConfig = Record<string, never>;\n");
  }

  // Generate env var name constants
  const separator = definition.separator ?? "_";
  const prefix = definition.prefix.toUpperCase();
  lines.push("export const ENV_VARS = {");

  const allPaths = flattenPaths(properties);
  for (const path of allPaths) {
    const envName =
      `${prefix}${separator}${path.replaceAll(".", separator)}`.toUpperCase();
    lines.push(`  "${path}": "${envName}",`);
  }

  // Add public env vars
  const publicPrefix = definition.publicPrefix ?? "";
  if (publicPrefix && publicKeys.length > 0) {
    for (const path of publicKeys) {
      const envName =
        `${publicPrefix.toUpperCase()}${prefix}${separator}${path.replaceAll(".", separator)}`.toUpperCase();
      lines.push(`  "public:${path}": "${envName}",`);
    }
  }

  lines.push("} as const;\n");

  return lines.join("\n");
};
