import type { ConfigDefinition } from "../types";

const HEADER = `// This file is auto-generated by @babytalk/standard-config
// Do not edit manually.

`;

const primitiveToTS = (type: string | undefined): string => {
  switch (type) {
    case "string": {
      return "string";
    }
    case "number":
    case "integer": {
      return "number";
    }
    case "boolean": {
      return "boolean";
    }
    case "null": {
      return "null";
    }
    default: {
      return "unknown";
    }
  }
};

const jsonSchemaTypeToTS = (schema: Record<string, unknown>): string => {
  const type = schema.type as string | string[] | undefined;

  if (Array.isArray(type)) {
    return type.map((t) => primitiveToTS(t)).join(" | ");
  }

  if (type === "object" && schema.properties) {
    const props = schema.properties as Record<string, Record<string, unknown>>;
    const required = schema.required as string[] | undefined;
    const req = new Set(required);
    const entries = Object.entries(props).map(([k, v]) => {
      const optional = req.has(k) ? "" : "?";
      return `${k}${optional}: ${jsonSchemaTypeToTS(v)}`;
    });
    return `{ ${entries.join("; ")} }`;
  }

  if (type === "array") {
    const items = schema.items as Record<string, unknown> | undefined;
    if (items) {
      return `${jsonSchemaTypeToTS(items)}[]`;
    }
    return "unknown[]";
  }

  return primitiveToTS(type);
};

/**
 * Generate a .gen.ts file content with Config and PublicConfig types,
 * plus an env var name map constant.
 */
export const generateTypeScript = (
  jsonSchema: Record<string, unknown>,
  definition: Pick<
    ConfigDefinition<unknown>,
    "prefix" | "public" | "separator" | "publicPrefix"
  >
): string => {
  const lines: string[] = [HEADER];

  // Generate Config type from JSON Schema properties
  const properties = (jsonSchema.properties ?? {}) as Record<
    string,
    Record<string, unknown>
  >;
  const required = jsonSchema.required as string[] | undefined;
  const requiredSet = new Set(required);

  lines.push("export interface Config {");
  for (const [key, prop] of Object.entries(properties)) {
    const tsType = jsonSchemaTypeToTS(prop);
    const optional = requiredSet.has(key) ? "" : "?";
    const description = prop.description as string | undefined;
    if (description) {
      lines.push(`  /** ${description} */`);
    }
    lines.push(`  ${key}${optional}: ${tsType};`);
  }
  lines.push("}\n");

  // Generate PublicConfig type
  const publicKeys = definition.public ?? [];
  if (publicKeys.length > 0) {
    const topLevelPublicKeys = publicKeys
      .map((k) => {
        const parts = k.split(".");
        return parts[0];
      })
      .filter((k) => k !== undefined)
      .filter((k, i, arr) => arr.indexOf(k) === i);

    const validKeys = topLevelPublicKeys.filter((k) => k in properties);
    if (validKeys.length > 0) {
      const pickKeys = validKeys.map((k) => `"${k}"`).join(" | ");
      lines.push(`export type PublicConfig = Pick<Config, ${pickKeys}>;\n`);
    } else {
      lines.push("export type PublicConfig = Record<string, never>;\n");
    }
  } else {
    lines.push("export type PublicConfig = Record<string, never>;\n");
  }

  return lines.join("\n");
};

interface EnvVarEntry {
  name: string;
  description?: string;
  hasDefault: boolean;
}

/**
 * Build the list of env var names (with descriptions) from a config definition and JSON Schema.
 */
const collectEnvVars = (
  properties: Record<string, Record<string, unknown>>,
  definition: Pick<
    ConfigDefinition<unknown>,
    "prefix" | "public" | "separator" | "publicPrefix"
  >
): EnvVarEntry[] => {
  const separator = definition.separator ?? "_";
  const prefix = definition.prefix.toUpperCase();
  const publicKeys = definition.public ?? [];
  const publicPrefix = definition.publicPrefix ?? "";
  const entries: EnvVarEntry[] = [];

  const collectFromProps = (
    props: Record<string, Record<string, unknown>>,
    parentPath = ""
  ) => {
    for (const [key, schema] of Object.entries(props)) {
      const currentPath = parentPath ? `${parentPath}.${key}` : key;
      if (schema.type === "object" && schema.properties) {
        collectFromProps(
          schema.properties as Record<string, Record<string, unknown>>,
          currentPath
        );
      } else {
        entries.push({
          description: schema.description as string | undefined,
          hasDefault: "default" in schema,
          name: `${prefix}${separator}${currentPath.replaceAll(".", separator)}`.toUpperCase(),
        });
      }
    }
  };

  collectFromProps(properties);

  if (publicPrefix && publicKeys.length > 0) {
    for (const path of publicKeys) {
      entries.push({
        description: `Public: ${path}`,
        hasDefault: false,
        name: `${publicPrefix.toUpperCase()}${prefix}${separator}${path.replaceAll(".", separator)}`.toUpperCase(),
      });
    }
  }

  return entries;
};

/**
 * Generate a .env.d.ts ambient declaration file for process.env and import.meta.env.
 */
export const generateEnvDeclaration = (
  jsonSchema: Record<string, unknown>,
  definition: Pick<
    ConfigDefinition<unknown>,
    "prefix" | "public" | "separator" | "publicPrefix"
  >
): string => {
  const properties = (jsonSchema.properties ?? {}) as Record<
    string,
    Record<string, unknown>
  >;
  const envVars = collectEnvVars(properties, definition);

  const lines: string[] = [
    "// This file is auto-generated by @babytalk/standard-config",
    "// Do not edit manually.",
    "",
    "export {};",
    "",
    "declare global {",
    "  interface ProcessEnv {",
  ];

  for (const entry of envVars) {
    if (entry.description) {
      lines.push(`    /** ${entry.description} */`);
    }
    const optional = entry.hasDefault ? "" : "?";
    lines.push(`    ${entry.name}${optional}: string;`);
  }

  lines.push("  }");
  lines.push("");
  lines.push("  interface ImportMetaEnv {");

  for (const entry of envVars) {
    if (entry.description) {
      lines.push(`    /** ${entry.description} */`);
    }
    const optional = entry.hasDefault ? "" : "?";
    lines.push(`    readonly ${entry.name}${optional}: string;`);
  }

  lines.push("  }");
  lines.push("");
  lines.push("  interface ImportMeta {");
  lines.push("    readonly env: ImportMetaEnv;");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
};
